Repository greensaleuz/greensale-webapi, pull requests merged in 2023-08, with the labels that each got.

#14 DATAACCES : User Add GetbyPhono
  src/GreenSale.DataAccess/Interfaces/Users/IUserRepository.cs
  src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
Labels: enhancement

#17 SERVISE : Service Auth AuthService Register
  src/GreenSale.Service/GreenSale.Service.csproj
  src/GreenSale.Service/Service/Auth/AuthServise.cs
Labels: enhancement, write

#18 SERVICE: TokenService and Development.json Created
  src/GreenSale.Service/GreenSale.Service.csproj
  src/GreenSale.Service/Service/Auth/TokenService.cs
  src/GreenSale.WebApi/appsettings.Development.json
Labels: no checked

#23 SERVISE : Service Auth AuthService Register
  src/GreenSale.DataAccess/Repositories/BaseRepository.cs
  src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
  src/GreenSale.Service/GreenSale.Service.csproj
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.WebApi/Configurations/Layers/DataAccessConfiguration.cs
  src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
  src/GreenSale.WebApi/Controllers/User/AuthController.cs
  src/GreenSale.WebApi/GreenSale.WebApi.csproj
  src/GreenSale.WebApi/Program.cs
Labels: enhancement, write

#35 SERVICE : Servise-Auth-Authservie-SendCodeForRegisterAsync
  src/GreenSale.Persistence/Dtos/Security/VerificationDto.cs
  src/GreenSale.Service/GreenSale.Service.csproj
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.Service/Service/Notifications/SmsSender.cs
  src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
  src/GreenSale.WebApi/Controllers/User/AuthController.cs
Labels: enhancement, write

#34 SERVICE: PasswordHasher Created
  src/GreenSale.Service/GreenSale.Service.csproj
  src/GreenSale.Service/Security/PasswordHasher.cs
Labels: no checked

#32 SERVICE: CodeGenerator Created
  src/GreenSale.Service/Helpers/CodeGenerator.cs
Labels: no checked

#30 MediaHelper Create
  src/GreenSale.Service/GreenSale.Service.csproj
  src/GreenSale.Service/Helpers/MediaHelper.cs
Labels: write

#24 CategoryService Created
  src/GreenSale.Service/GreenSale.Service.csproj
  src/GreenSale.Service/Service/Categories/CategoryService.cs
Labels: no checked

#28 SERVICE:FileService (Delete func) Created
  src/GreenSale.Service/Interfaces/Common/IFileService.cs
  src/GreenSale.Service/Service/Common/FileService.cs
Labels: no checked

#21 IdentityService Created
  src/GreenSale.Service/Service/Auth/IdentityService.cs
Labels: no checked

#38 SERVICE : Servise-Auth-Authservie-VerifyRegisterAsync
  src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
  src/GreenSale.Domain/Entites/Users/User.cs
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.Service/Service/Notifications/SmsSender.cs
  src/GreenSale.WebApi/Controllers/User/AuthController.cs
Labels: enhancement

#43 CategoryControler and PaginatorService Created
  src/GreenSale.DataAccess/Repositories/BaseRepository.cs
  src/GreenSale.Service/GreenSale.Service.csproj
  src/GreenSale.Service/Security/PasswordHasher.cs
  src/GreenSale.Service/Service/Common/Pagination.cs
  src/GreenSale.WebApi/Configurations/Layers/DataAccessConfiguration.cs
  src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
  src/GreenSale.WebApi/Controllers/Admin/Categories/CategoryController.cs
  src/GreenSale.WebApi/Controllers/WeatherForecastController.cs
  src/GreenSale.WebApi/Program.cs
Labels: no checked

#46 Full CategoryController Created
  src/GreenSale.Domain/Entites/Categories/Category.cs
  src/GreenSale.Persistence/Validators/Categories/CategoryCreateValidator.cs
  src/GreenSale.Service/Interfaces/Categories/ICategoryService.cs
  src/GreenSale.Service/Service/Categories/CategoryService.cs
  src/GreenSale.WebApi/Controllers/Admin/Categories/CategoryController.cs
Labels: no checked

#48 WEBAPI : Add Auth Controller Validayion
  src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
  src/GreenSale.Persistence/Validators/Dtos/AuthUserValidators/UserLoginValidator.cs
  src/GreenSale.Persistence/Validators/Dtos/AuthUserValidators/UserRegisterValidator.cs
  src/GreenSale.WebApi/Controllers/User/AuthController.cs
Labels: no checked

#40 WEPAPI : Auth Login
  src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
  src/GreenSale.Service/Helpers/CodeGenerator.cs
  src/GreenSale.Service/Helpers/MediaHelper.cs
  src/GreenSale.Service/Interfaces/Auth/ITokenService.cs
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.Service/Service/Auth/IdentityService.cs
  src/GreenSale.Service/Service/Auth/TokenService.cs
  src/GreenSale.Service/Service/Categories/CategoryService.cs
  src/GreenSale.Service/Service/Common/FileService.cs
  src/GreenSale.Service/Service/Notifications/SmsSender.cs
  src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
  src/GreenSale.WebApi/Controllers/User/AuthController.cs
  src/GreenSale.WebApi/Program.cs
Labels: enhancement

#53 CODE RUB Config corected
  src/GreenSale.Service/Security/PasswordHasher.cs
  src/GreenSale.Service/Service/Categories/CategoryService.cs
Labels: bug, CODE RUB

#52 Middleware Created
  src/GreenSale.WebApi/Middlewares/ExceptionHandlerMiddleware.cs
  src/GreenSale.WebApi/Program.cs
Labels: write

#55 WEP-API Architekture Controller
  src/GreenSale.WebApi/Controllers/Admin/AdminBaseController.cs
  src/GreenSale.WebApi/Controllers/Admin/Categories/CategoryController.cs
  src/GreenSale.WebApi/Controllers/Common/Auth/AuthController.cs
  src/GreenSale.WebApi/Controllers/Common/BaseController.cs
Labels: no checked

#57 RoleService and RoleException Created
  src/GreenSale.Application/Exceptions/Roles/RoleNotFoundException.cs
  src/GreenSale.Service/Interfaces/Roles/IRoleService.cs
  src/GreenSale.Service/Service/Categories/CategoryService.cs
  src/GreenSale.Service/Service/Roles/RoleService.cs
Labels: no checked

#63 PERSISTENCE: StorageCretaeValidator Create
  src/GreenSale.Persistence/Common/Helpers/MediaHelper.cs
  src/GreenSale.Persistence/Dtos/StoragDtos/StoragCreateDto.cs
  src/GreenSale.Persistence/Validators/Storages/StorageCreateValidator.cs
Labels: write

#67 StorageService , FileService(UploadImage func) and ImageNotFoundExcep…
  src/GreenSale.Application/Exceptions/ImageNotFoundException.cs
  src/GreenSale.Service/Service/Common/FileService.cs
  src/GreenSale.Service/Service/Storages/StorageService.cs
Labels: no checked

#41 Service identity service
  src/GreenSale.Service/Service/Auth/IdentityService.cs
Labels: no checked

#61 UNITTEST : Vlidators Phone Number Test
  GreenSale.Platform.sln
  src/GreenSale.Application/Exceptions/Roles/RoleNotFoundException.cs
  src/GreenSale.Service/Interfaces/Roles/IRoleService.cs
  src/GreenSale.Service/Service/Categories/CategoryService.cs
  src/GreenSale.Service/Service/Roles/RoleService.cs
  src/GreenSale.WebApi/Controllers/Admin/AdminBaseController.cs
  src/GreenSale.WebApi/Controllers/Admin/Categories/CategoryController.cs
  src/GreenSale.WebApi/Controllers/Common/Auth/AuthController.cs
  src/GreenSale.WebApi/Controllers/Common/BaseController.cs
  src/GreenSale.WebApi/Middlewares/ExceptionHandlerMiddleware.cs
  test/GreenSale.Test/GreenSale.Test.csproj
  test/GreenSale.Test/Usings.cs
  test/GreenSale.Test/ValidatorsTest/AuthTest/UserLoginValidatorTest.cs
  test/GreenSale.Test/ValidatorsTest/AuthTest/UserRegisterValidatorTests.cs
  test/GreenSale.Test/ValidatorsTest/PasswordTest.cs
  test/GreenSale.Test/ValidatorsTest/PhoneNumberTest.cs
Labels: no checked

#72 TEST : Validator Test
  test/GreenSale.Test/ValidatorsTest/CategoryTest/CategoryValidatorTest.cs
  test/GreenSale.Test/ValidatorsTest/Roles/RoleValidatorTest.cs
  test/GreenSale.Test/ValidatorsTest/Storages/StorageCreatedValidatorTest.cs
  test/GreenSale.Test/ValidatorsTest/Storages/StorageUpdatedValidatorTest.cs
Labels: no checked

#74 User Created Full
  src/GreenSale.Application/Exceptions/ImageNotFoundException.cs
  src/GreenSale.DataAccess/Repositories/Roles/RoleRepositories.cs
  src/GreenSale.Persistence/Validators/Roles/RoleValidator.cs
  src/GreenSale.Persistence/Validators/Storages/StorageCreateValidator.cs
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.Service/Service/Auth/TokenService.cs
  src/GreenSale.Service/Service/Common/FileService.cs
  src/GreenSale.Service/Service/Notifications/SmsSender.cs
  src/GreenSale.Service/Service/Storages/StorageService.cs
  src/GreenSale.WebApi/Configurations/Layers/CorsPolicyConfiguration.cs
  src/GreenSale.WebApi/Configurations/Layers/DataAccessConfiguration.cs
  src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
  src/GreenSale.WebApi/Controllers/Admin/Roles/RoleController.cs
  src/GreenSale.WebApi/Controllers/Common/Storages/StorageController.cs
  src/GreenSale.WebApi/Program.cs
Labels: no checked

#78 WEBAPI: Controller Super Admin
  src/GreenSale.Application/Exceptions/Roles/UserRoleNotFoundException.cs
  src/GreenSale.Persistence/Dtos/RoleDtos/UserRoleDtoUpdate.cs
  src/GreenSale.Service/Interfaces/Roles/IUserRoleService.cs
  src/GreenSale.Service/Service/Roles/UserRoleService.cs
  src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
  src/GreenSale.WebApi/Controllers/Admin/AdminBaseController.cs
  src/GreenSale.WebApi/Controllers/Admin/Categories/AdminCategoriesController.cs
  src/GreenSale.WebApi/Controllers/Admin/Roles/AdminRolesController.cs
  src/GreenSale.WebApi/Controllers/Client/ClientStoragesController.cs
  src/GreenSale.WebApi/Controllers/Common/Storages/CommonStoragesController.cs
  src/GreenSale.WebApi/Controllers/Heat/Roles/SuperAdminRolesController.cs
  src/GreenSale.WebApi/Controllers/Heat/Roles/SuperAdminUsersRoleController.cs
  src/GreenSale.WebApi/Controllers/Heat/SuperAdminBaseController.cs
Labels: no checked

#80 WEBAPI : auftariza Super Admin And Admin
  src/GreenSale.DataAccess/Interfaces/Roles/IUserRoles.cs
  src/GreenSale.DataAccess/Repositories/Roles/UserRoleRepository.cs
  src/GreenSale.DataAccess/ViewModels/UserRoles/UserRoleViewModel.cs
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.WebApi/Configurations/CorsPolicyConfiguration.cs
  src/GreenSale.WebApi/Configurations/JwtConfiguration.cs
  src/GreenSale.WebApi/Configurations/SwaggerAuthConfiguration.cs
  src/GreenSale.WebApi/GreenSale.WebApi.csproj
  src/GreenSale.WebApi/Program.cs
Labels: no checked

#82 CODE RUB : Authtariza User To Admin
  src/GreenSale.DataAccess/Repositories/Roles/UserRoleRepository.cs
  src/GreenSale.Service/Service/Roles/UserRoleService.cs
  src/GreenSale.WebApi/Configurations/JwtConfiguration.cs
  src/GreenSale.WebApi/Controllers/Heat/SuperAdminBaseController.cs
  src/GreenSale.WebApi/appsettings.json
Labels: no checked

#84 SERVICE : User Interface and User Service Created
  src/GreenSale.Service/Interfaces/Users/IUserService.cs
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.Service/Service/Users/UserService.cs
Labels: no checked

#86 PERSISTENCE : Valodators User Update Validators
  src/GreenSale.Persistence/Dtos/UserDtos/UserUpdateDto.cs
  src/GreenSale.Persistence/Validators/Users/UserUpdateValidator.cs
  src/GreenSale.Service/Interfaces/Users/IUserService.cs
  src/GreenSale.Service/Service/Users/UserService.cs
Labels: no checked

#88 WEBAPI : SuperAdmin and Admin Controller complate
  src/GreenSale.WebApi/Configurations/JwtConfiguration.cs
  src/GreenSale.WebApi/Controllers/Admin/AdminBaseController.cs
  src/GreenSale.WebApi/Controllers/Admin/Roles/AdminRolesController.cs
  src/GreenSale.WebApi/Controllers/Admin/Users/AdminUsersController.cs
  src/GreenSale.WebApi/Controllers/Auth/AuthController.cs
  src/GreenSale.WebApi/Controllers/Client/BaseClientController.cs
  src/GreenSale.WebApi/Controllers/Client/ClientAccountController.cs
  src/GreenSale.WebApi/Controllers/SuperAdmin/Roles/SuperAdminRolesController.cs
  src/GreenSale.WebApi/Controllers/SuperAdmin/Roles/SuperAdminUsersRoleController.cs
  src/GreenSale.WebApi/Controllers/SuperAdmin/SuperAdminBaseController.cs
Labels: no checked

#89 CODE RUB : Corect
  src/GreenSale.WebApi/Controllers/Admin/Users/AdminUsersController.cs
  src/GreenSale.WebApi/Controllers/Client/ClientAccountController.cs
Labels: no checked

#92 Write sellerPost Servise, and Code rub IFILE Service , ISellePostService
  src/GreenSale.Persistence/Dtos/SellerPostImageUpdateDtos/SellerPostImageUpdateDto.cs
  src/GreenSale.Persistence/Dtos/SellerPostsDtos/SellerPostUpdateDto.cs
  src/GreenSale.Service/Interfaces/SellerPosts/ISellerPostService.cs
  src/GreenSale.Service/Service/Auth/IdentityService.cs
  src/GreenSale.Service/Service/Common/FileService.cs
  src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs
  src/GreenSale.WebApi/GreenSale.WebApi.csproj
Labels: no checked

#94 SERVICE : Buyer Post Service Create
  src/GreenSale.Persistence/Dtos/BuyerPostImageUpdateDtos/BuyerPostImageDto.cs
  src/GreenSale.Service/Interfaces/BuyerPosts/IBuyerPostService.cs
  src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
Labels: no checked

#96 WEBAPI : Seller Post Controller
  src/GreenSale.DataAccess/Repositories/SellerPosts/SellerPostImageRepository.cs
  src/GreenSale.DataAccess/Repositories/SellerPosts/SellerPostRepository.cs
  src/GreenSale.Domain/Entites/SellerPosts/SellerPostImage.cs
  src/GreenSale.Service/Interfaces/Users/IUserService.cs
  src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs
  src/GreenSale.Service/Service/Users/UserService.cs
  src/GreenSale.WebApi/Configurations/Layers/DataAccessConfiguration.cs
  src/GreenSale.WebApi/Configurations/Layers/ServiceLayerConfiguration.cs
  src/GreenSale.WebApi/Controllers/Admin/Users/AdminUsersController.cs
  src/GreenSale.WebApi/Controllers/Client/ClientAccountController.cs
  src/GreenSale.WebApi/Controllers/Client/SellerPosts/ClientSellerPostController.cs
  src/GreenSale.WebApi/Controllers/Client/Storages/ClientStoragesController.cs
  src/GreenSale.WebApi/Controllers/Common/Categories/CommonCategoriesController.cs
  src/GreenSale.WebApi/Controllers/Common/SellerPosts/CommonSellerPostController.cs
  src/GreenSale.WebApi/Controllers/Common/Storages/CommonStoragesController.cs
  src/GreenSale.WebApi/Program.cs
Labels: write, no checked, CODE RUB

#106 CODE RUB : All Project
  src/GreenSale.DataAccess/Interfaces/Roles/IUserRoles.cs
  src/GreenSale.DataAccess/ViewModels/UserRoles/UserRoleViewModel.cs
  src/GreenSale.Persistence/Dtos/SellerPostsDtos/SellerPostUpdateDto.cs
  src/GreenSale.Persistence/Validators/BuyerPosts/BuyerPostUpdateValidator.cs
  src/GreenSale.Service/Interfaces/BuyerPosts/IBuyerPostService.cs
  src/GreenSale.Service/Interfaces/Roles/IUserRoleService.cs
  src/GreenSale.Service/Interfaces/Users/IUserService.cs
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
  src/GreenSale.Service/Service/Common/FileService.cs
  src/GreenSale.Service/Service/Roles/UserRoleService.cs
  src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs
  src/GreenSale.Service/Service/Users/UserService.cs
  src/GreenSale.WebApi/Configurations/Layers/DataAccessConfiguration.cs
  src/GreenSale.WebApi/Controllers/Admin/AdminBaseController.cs
  src/GreenSale.WebApi/Controllers/Admin/Users/AdminUsersController.cs
  src/GreenSale.WebApi/Controllers/Client/BaseClientController.cs
  src/GreenSale.WebApi/Controllers/Client/BuyerPosts/ClientBuyerPostsController.cs
  src/GreenSale.WebApi/Controllers/Client/ClientAccountController.cs
  src/GreenSale.WebApi/Controllers/Client/SellerPosts/ClientSellerPostController.cs
  src/GreenSale.WebApi/Controllers/Common/BuyerPosts/CommonBuyerPostsController.cs
  src/GreenSale.WebApi/Controllers/Common/Categories/CommonCategoriesController.cs
  src/GreenSale.WebApi/Controllers/Common/SellerPosts/CommonSellerPostController.cs
  src/GreenSale.WebApi/Controllers/Common/Storages/CommonStoragesController.cs
  src/GreenSale.WebApi/Controllers/SuperAdmin/SuperAdminBaseController.cs
  test/GreenSale.Test/ValidatorsTest/CategoryTest/CategoryValidatorTest.cs
  test/GreenSale.Test/ValidatorsTest/Roles/RoleValidatorTest.cs
  test/GreenSale.Test/ValidatorsTest/Storages/StorageCreatedValidatorTest.cs
Labels: no checked

#105 corrected
  src/GreenSale.WebApi/Controllers/Client/BuyerPosts/ClientBuyerPostsController.cs
  src/GreenSale.WebApi/Controllers/Common/BuyerPosts/CommonBuyerPostsController.cs
Labels: no checked

#108 CODE RUB : Controller
  src/GreenSale.DataAccess/Interfaces/Roles/IUserRoles.cs
  src/GreenSale.WebApi/Controllers/Client/BuyerPosts/ClientBuyerPostsController.cs
  src/GreenSale.WebApi/Controllers/Client/SellerPosts/ClientSellerPostController.cs
  src/GreenSale.WebApi/Controllers/Common/BuyerPosts/CommonBuyerPostsController.cs
Labels: no checked

#109 CODE RUB : BuyerPostsRepository And TimeConstant and BuyerPostEnum An…
  src/GreenSale.DataAccess/Interfaces/BuyerPosts/IBuyerPostImageRepository.cs
  src/GreenSale.DataAccess/Repositories/BuyerPosts/BuyerPostImageRepository.cs
  src/GreenSale.DataAccess/Repositories/BuyerPosts/BuyerPostsRepository.cs
  src/GreenSale.DataAccess/ViewModels/BuyerPosts/BuyerPostViewModel.cs
  src/GreenSale.Domain/Constants/TimeConstant.cs
  src/GreenSale.Domain/Enums/BuyerPosts/BuyerPostEnum.cs
  src/GreenSale.Persistence/Dtos/BuyerPostsDto/BuyerPostCreateDto.cs
  src/GreenSale.Persistence/Dtos/BuyerPostsDto/BuyerPostUpdateDto.cs
  src/GreenSale.Persistence/Validators/BuyerPosts/BuyerPostCreateValidator.cs
  src/GreenSale.Persistence/Validators/BuyerPosts/BuyerPostUpdateValidator.cs
  src/GreenSale.Service/Interfaces/Common/IFileService.cs
  src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
  src/GreenSale.Service/Service/Common/FileService.cs
  src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs
  src/GreenSale.Service/Service/Storages/StorageService.cs
  src/GreenSale.WebApi/Controllers/Client/BuyerPosts/ClientBuyerPostsController.cs
  src/GreenSale.WebApi/GreenSale.WebApi.csproj
Labels: no checked, CODE RUB

#112 WEBAPI : Client Controller Get User
  src/GreenSale.DataAccess/Repositories/Users/UserRepository.cs
  src/GreenSale.DataAccess/ViewModels/Users/UserViewModel.cs
  src/GreenSale.Service/Service/Users/UserService.cs
  src/GreenSale.WebApi/Controllers/Client/BaseClientController.cs
  src/GreenSale.WebApi/Controllers/Client/ClientAccountController.cs
Labels: no checked

#117 WEBAPI : Auth Token Verify
  src/GreenSale.Service/Interfaces/Auth/IAuthServices.cs
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.Service/Service/Auth/TokenService.cs
  src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
  src/GreenSale.WebApi/Controllers/Auth/AuthController.cs
  src/GreenSale.WebApi/Controllers/Client/BaseClientController.cs
  src/GreenSale.WebApi/GreenSale.WebApi.csproj
Labels: no checked

#133 TEST : BuyerPostUpdateValidator Test
  test/GreenSale.Test/ValidatorsTest/BuyerPostTests/BuyerPostUpdateValidatorTest.cs
Labels: no checked

#147 CODE RUB : Security
  src/GreenSale.Service/Service/Auth/AuthServise.cs
  src/GreenSale.Service/Service/Auth/TokenService.cs
Labels: CODE RUB

#153 CODE RUB : Service Chek Found
  src/GreenSale.Service/Service/BuyerPosts/BuyerPostService.cs
  src/GreenSale.Service/Service/Roles/UserRoleService.cs
  src/GreenSale.Service/Service/SellerPosts/SellerPostService.cs
  src/GreenSale.Service/Service/Storages/StorageService.cs
Labels: CODE RUB
